baseURL = "https://sleepy-haibt-9110b8.netlify.app/"
languageCode = "en-us"
title = "SigChain Capital"

theme = "github.com/zzossig/hugo-theme-zdoc"

pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsStyle = "monokai"
pygmentsUseClasses = false

copyright = "This is my {} copyright text"


[module]

[[module.mounts]]
  source = "layouts"
  target = "layouts"

[[module.mounts]]
  source = "static"
  target = "static"

[[module.mounts]]
  source = "assets"
  target = "assets"

[[module.mounts]]
  source = "content"
  target = "content"

[[module.mounts]]
  source = "archetypes"
  target = "archetypes"

[[module.mounts]]
  source = "data"
  target = "data"


[outputs]
  home = ["HTML", "RSS", "SearchIndex"]
  section = ["HTML", "RSS", "SearchIndex"]
  taxonomyTerm = ["HTML", "RSS", "SearchIndex"]
  taxonomy = ["HTML", "RSS", "SearchIndex"]

[outputFormats]
  [outputFormats.SearchIndex]
    mediaType = "application/json"
    baseName = "index"
    isPlainText = true
    notAlternative = true