[[main]]
  identifier = "about"
  name = "About"
  url = "/main/"
  weight = 10


[[main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact"
  weight = 50

[[main]]
  identifier = "autonomous"
  name = "Autonomous Web & Finance"
  url = "/autonomous"
  weight = 60
